# Generated by Django 3.1.2 on 2021-11-20 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radiusMean', models.DecimalField(decimal_places=10, max_digits=10)),
                ('textureMean', models.DecimalField(decimal_places=10, max_digits=10)),
                ('perimeterMean', models.DecimalField(decimal_places=10, max_digits=10)),
                ('areaMean', models.DecimalField(decimal_places=10, max_digits=10)),
                ('smoothnessMean', models.DecimalField(decimal_places=10, max_digits=10)),
                ('compactnessMean', models.DecimalField(decimal_places=10, max_digits=10)),
                ('concavityMean', models.DecimalField(decimal_places=10, max_digits=10)),
                ('concavePointMean', models.DecimalField(decimal_places=10, max_digits=10)),
                ('symmetryMean', models.DecimalField(decimal_places=10, max_digits=10)),
                ('fractalDimensionMean', models.DecimalField(decimal_places=10, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
