# Generated by Django 3.1.2 on 2021-11-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BreastCancerPrediction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='areaMean',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='compactnessMean',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='concavePointMean',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='concavityMean',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='fractalDimensionMean',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='perimeterMean',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='radiusMean',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='smoothnessMean',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='symmetryMean',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='textureMean',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
